// CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY';

// PRODUCT
export const VOTE_PRODUCT = 'VOTE_PRODUCT';
export const CHANGE_STOCK_NUMBER = 'CHANGE_STOCK_NUMBER';

// ADMIN
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';